# Generated by Django 4.2 on 2024-07-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
