# Generated by Django 4.2 on 2024-07-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytienda', '0002_remove_producto_stock_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
