# Generated by Django 4.2 on 2024-07-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytienda', '0006_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
